[2024-06-28T03:57:00.520+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T03:57:00.587+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.fetch_weather_data manual__2024-06-28T03:56:50.826976+00:00 [queued]>
[2024-06-28T03:57:00.605+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.fetch_weather_data manual__2024-06-28T03:56:50.826976+00:00 [queued]>
[2024-06-28T03:57:00.606+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T03:57:00.632+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_weather_data> on 2024-06-28 03:56:50.826976+00:00
[2024-06-28T03:57:00.645+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=104) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-28T03:57:00.652+0000] {standard_task_runner.py:63} INFO - Started process 113 to run task
[2024-06-28T03:57:00.649+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'fetch_weather_data', 'manual__2024-06-28T03:56:50.826976+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpdttrofns']
[2024-06-28T03:57:00.653+0000] {standard_task_runner.py:91} INFO - Job 22: Subtask fetch_weather_data
[2024-06-28T03:57:00.775+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_pipeline.fetch_weather_data manual__2024-06-28T03:56:50.826976+00:00 [running]> on host 2efad63007cb
[2024-06-28T03:57:00.964+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='fetch_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T03:56:50.826976+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T03:56:50.826976+00:00'
[2024-06-28T03:57:00.966+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T03:57:01.363+0000] {python.py:237} INFO - Done. Returned value was: ./data/weather_data_paris_20240628035701.csv
[2024-06-28T03:57:01.364+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T03:57:01.410+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=fetch_weather_data, run_id=manual__2024-06-28T03:56:50.826976+00:00, execution_date=20240628T035650, start_date=20240628T035700, end_date=20240628T035701
[2024-06-28T03:57:01.478+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T03:57:01.535+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-28T03:57:01.541+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
