[2024-06-28T11:00:30.647+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T11:00:30.666+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.train_model manual__2024-06-28T11:00:23.233760+00:00 [queued]>
[2024-06-28T11:00:30.676+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.train_model manual__2024-06-28T11:00:23.233760+00:00 [queued]>
[2024-06-28T11:00:30.676+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T11:00:30.693+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_model> on 2024-06-28 11:00:23.233760+00:00
[2024-06-28T11:00:30.700+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1518) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-28T11:00:30.702+0000] {standard_task_runner.py:63} INFO - Started process 1532 to run task
[2024-06-28T11:00:30.701+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'train_model', 'manual__2024-06-28T11:00:23.233760+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpv4nkg7se']
[2024-06-28T11:00:30.703+0000] {standard_task_runner.py:91} INFO - Job 111: Subtask train_model
[2024-06-28T11:00:30.760+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_pipeline.train_model manual__2024-06-28T11:00:23.233760+00:00 [running]> on host 4200b9de651c
[2024-06-28T11:00:30.852+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T11:00:23.233760+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T11:00:23.233760+00:00'
[2024-06-28T11:00:30.853+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T11:00:31.077+0000] {warnings.py:112} WARNING - /opt/***/scripts/train_model.py:16: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['temperature_2m'].fillna(method='ffill', inplace=True)

[2024-06-28T11:00:31.134+0000] {logging_mixin.py:188} INFO - Mean Squared Error: 7.210475408331276
[2024-06-28T11:00:31.152+0000] {logging_mixin.py:188} INFO - R-squared: 0.8558007380909088
[2024-06-28T11:00:31.155+0000] {logging_mixin.py:188} INFO - Model has been saved to ./temperature_prediction_model.pkl
[2024-06-28T11:00:31.156+0000] {python.py:237} INFO - Done. Returned value was: ./temperature_prediction_model.pkl
[2024-06-28T11:00:31.157+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T11:00:31.189+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=train_model, run_id=manual__2024-06-28T11:00:23.233760+00:00, execution_date=20240628T110023, start_date=20240628T110030, end_date=20240628T110031
[2024-06-28T11:00:31.238+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T11:00:31.258+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-28T11:00:31.261+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
